Song.create(title: 'Mortified', stream_url: "https://api.soundcloud.com/tracks/184532324/stream", mood: "Happy")
Song.create(title: 'Sequentiality', stream_url: "https://api.soundcloud.com/tracks/184532322/stream", mood: "Chill")
Song.create(title: 'You Have Chosen Wisely', stream_url: "https://api.soundcloud.com/tracks/184532318/stream", mood: "Angry")
Song.create(title: 'Mortified', stream_url: "https://api.soundcloud.com/tracks/184532324/stream", mood: "Chill")
Song.create(title: 'Sequentiality', stream_url: "https://api.soundcloud.com/tracks/184532322/stream", mood: "Angry")
Song.create(title: 'You Have Chosen Wisely', stream_url: "https://api.soundcloud.com/tracks/184532318/stream", mood: "Happy")
Song.create(title: 'Mortified', stream_url: "https://api.soundcloud.com/tracks/184532324/stream", mood: "Angry")
Song.create(title: 'Sequentiality', stream_url: "https://api.soundcloud.com/tracks/184532322/stream", mood: "Happy")
Song.create(title: 'You Have Chosen Wisely', stream_url: "https://api.soundcloud.com/tracks/184532318/stream", mood: "Chill")
